/**
 * Version Dashboard API Endpoint
 *
 * Returns current version information and deployment history
 * RBAC: SuperAdmin only (isSuperAdmin = true)
 *
 * Response:
 * - current: { appVersion, swVersion, buildId, gitSha, branch, environment }
 * - deployments: Array of last 20 deployments
 */

import { NextResponse } from 'next/server';
import { auth } from '@/auth';
import fs from 'fs';
import path from 'path';

export async function GET() {
  try {
    const session = await auth();

    // RBAC: SuperAdmin only
    if (!session || !session.user.isSuperAdmin) {
      return NextResponse.json(
        { error: 'Unauthorized - SuperAdmin access required' },
        { status: 403 }
      );
    }

    // Read version.json
    const versionPath = path.join(process.cwd(), 'version.json');
    if (!fs.existsSync(versionPath)) {
      return NextResponse.json(
        { error: 'version.json not found' },
        { status: 500 }
      );
    }

    const versionData = JSON.parse(fs.readFileSync(versionPath, 'utf8'));

    // Read build-info.json if exists (generated by generate-build-id.sh)
    const buildInfoPath = path.join(process.cwd(), 'public/build-info.json');
    let buildInfo = null;
    if (fs.existsSync(buildInfoPath)) {
      try {
        buildInfo = JSON.parse(fs.readFileSync(buildInfoPath, 'utf8'));
      } catch (error) {
        console.warn('Failed to read build-info.json:', error);
      }
    }

    // Extract git SHA from build ID (format: YYYY-MM-DD-gitsha)
    const buildId = process.env.NEXT_PUBLIC_BUILD_ID || 'dev-local';
    const gitSha = buildId.includes('-')
      ? buildId.split('-').pop() || 'unknown'
      : buildInfo?.gitSha || 'unknown';

    const response = {
      current: {
        appVersion: versionData.version,
        swVersion: versionData.serviceWorkerVersion,
        buildId,
        gitSha,
        branch: versionData.branch || 'unknown',
        environment: process.env.RAILWAY_ENVIRONMENT || 'local',
      },
      deployments: versionData.deployments || [],
    };

    return NextResponse.json(response, {
      headers: {
        'Cache-Control': 'no-store, must-revalidate',
        'Pragma': 'no-cache',
      },
    });
  } catch (error) {
    console.error('[API /version/dashboard] Error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
